[custom]
;基于[@ACL4SSR](https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.ini)修改
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 广告拦截,[]GEOSITE,category-ads-all
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.list
;ruleset=🔗 ProxyDNS,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DNS/DNS.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list
;ruleset=🎯 全球直连,[]GEOSITE,category-games@cn
ruleset=🎯 全球直连,clash-classic:https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/ChinaDownloadCDN.yaml
ruleset=🖥️ 国际CDN下载,clash-classic:https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/InternationalDownloadCDN.yaml
#常见的游戏厂商直连域名
ruleset=💬 OpenAi,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=💬 OpenAi,clash-classic:https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/AI.yaml
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🕹️ Nintendo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Origin/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list
;ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
;ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🐰 Disney视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
;ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
;ruleset=📹 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=📹 TikTok,clash-classic:https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/TikTok.yaml
ruleset=🌍 国外媒体,[]DOMAIN-SUFFIX,user.mypikpak.com
ruleset=🌍 国外媒体,[]DOMAIN-SUFFIX,rcv5-sp.mypikpak.com
ruleset=🌍 国外媒体,[]DOMAIN-SUFFIX,config.mypikpak.com
ruleset=🌍 国外媒体,[]DOMAIN-SUFFIX,api-drive.mypikpak.com
ruleset=🌍 国外媒体,[]DOMAIN-SUFFIX,access.mypikpak.com
ruleset=🌍 国外媒体,[]DOMAIN-SUFFIX,hubciddata.mypikpak.com
ruleset=📖 PikPak,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.list
ruleset=🎬 EmbyProxy,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.list
ruleset=🎬 EmbyProxy,https://raw.githubusercontent.com/Pegasus02/Clash_Rules/main/list/Nebula.list
ruleset=🎬 EmbyProxy,https://raw.githubusercontent.com/ddgksf2013/Filter/master/Emby.list
;ruleset=🎬 EmbyProxy,https://raw.githubusercontent.com/MisakaFxxk/MisakaF_Subconverter/main/Sub/Emby.list
;ruleset=🎬 EmbyProxy,https://raw.githubusercontent.com/MisakaFxxk/MisakaF_Subconverter/main/Sub/EmbyVip.list
;ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
;ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBiliIntl/BiliBiliIntl.list
;ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list
ruleset=🔑️ 1Password,https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/1PasswordUS.list
;美国数据中心
;ruleset=🔑️ 1Password,https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/1PasswordEU.list
;欧盟数据中心
;ruleset=🔑️ 1Password,https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/1PasswordCA.list
;加拿大数据中心
ruleset=🛡️ ESET,clash-classic:https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/ESET_China.yaml
;ruleset=🛡️ ESET,clash-classic:https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/ESET.yaml
ruleset=⚡ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=⛏ Developer,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Developer/Developer.list
ruleset=⛏ Developer,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=⛏ Developer,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitBook/GitBook.list
ruleset=⛏ Developer,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Docker/Docker.list
ruleset=⛏ Developer,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Scholar/Scholar.list
;ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
;ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
;ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
;ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
;ruleset=📢 谷歌🇨🇳Play下载,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
;ruleset=📢 谷歌🇨🇳Play服务,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=📢 谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonCN/AmazonCN.list
ruleset=🏪 国际电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon.list
ruleset=🏪 国际电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/eBay/eBay.list
ruleset=🏪 国际电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bestbuy/Bestbuy.list
ruleset=🏪 国际电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Shopify/Shopify.list
;ruleset=☁ cloudflare,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflare/Cloudflare.list
;ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
;ruleset=📲 电报消息,https://raw.githubusercontent.com/LucaLin233/Luca_Conf/main/Surge/Rule/Telegram.list
;ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
;ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
;;ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ProxyLite/ProxyLite.list
;ruleset=🎯 全球直连,clash-domain:https://raw.githubusercontent.com/yuumimi/rules/release/clash/geolocation-!cn@cn.txt
;ruleset=🚀 节点选择,clash-domain:https://raw.githubusercontent.com/yuumimi/rules/release/clash/cn@!cn.txt
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,portcheck.transmissionbt.com
;Transmission检测地址
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
ruleset=🌍 国外媒体,[]DOMAIN-SUFFIX,fsm.name
ruleset=🎯 全球直连,clash-domain:https://raw.githubusercontent.com/ixff/clash-rules/release/category-pt.txt
;ruleset=🚀 节点选择,clash-domain:https://raw.githubusercontent.com/yuumimi/rules/release/clash/geolocation-!cn.txt
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
;ruleset=🎯 全球直连,clash-domain:https://raw.githubusercontent.com/yuumimi/rules/release/clash/cn.txt
ruleset=🎯 全球直连,[]GEOSITE,cn
;域名集合
;;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,cn
;ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
;no-resolve 选项用来指定当规则中出现域名时，不进行DNS解析转换成IP来匹配，而是直接使用域名进行匹配。如果规则中指定的是IP地址，那么就会直接使用这个IP地址进行匹配
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]🚀 手动切换`[]♻️ 自动选择`[]🔮 负载均衡`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
;custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.apple.com/library/test/success.html`300,,10
custom_proxy_group=♻️ 自动选择`url-test`(^(?!.*(Traffic|Expire)).*)`http://www.apple.com/library/test/success.html`300,,10
custom_proxy_group=🔮 负载均衡`load-balance`(HKG|Hong Kong|香港 IEPL|香港高级|高级 专线 香港)`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🔗 ProxyDNS`select`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择`[]🔮 负载均衡`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略`[]DIRECT
custom_proxy_group=🖥️ 国际CDN下载`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略`(实验性)
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
ustom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=📢 谷歌服务`select`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=🏪 国际电商`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🧭 特殊节点`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
;custom_proxy_group=☁ cloudflare`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=💬 OpenAi`select`[]🚀 节点选择`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]🚀 手动切换`[]📹 油管节点`[]🧭 特殊节点`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=🎥 奈飞视频`select`[]🚀 节点选择`[]🚀 手动切换`[]🎥 奈飞节点`[]🧭 特殊节点`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=🐰 Disney视频`select`[]🚀 节点选择`[]🚀 手动切换`[]🐰 Disney节点`[]🧭 特殊节点`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=📺 巴哈姆特`select`[]🚀 节点选择`[]🚀 手动切换`[]🇨🇳 台湾策略
custom_proxy_group=📹 TikTok`select`[]🚀 节点选择`[]🚀 手动切换`[]🧭 特殊节点`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略`(实验性)
custom_proxy_group=📖 PikPak`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略`[]🎥 奈飞节点`[]🐰 Disney节点`[]📹 油管节点
custom_proxy_group=🎬 EmbyProxy`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🎬 Emby节点`[]🧭 特殊节点`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=📺 哔哩哔哩`select`[]DIRECT`[]🇭🇰 香港策略`[]🇨🇳 台湾策略
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇸🇬 狮城策略`[]🇯🇵 日本策略`[]🚀 手动切换
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🚀 手动切换`[]🎥 奈飞节点`[]🐰 Disney节点`[]📹 油管节点`[]🧭 特殊节点`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略`(实验性)
custom_proxy_group=🕹️ Nintendo`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🔮 负载均衡`[]🧭 特殊节点`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🔮 负载均衡`[]🧭 特殊节点`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=🔑️ 1Password`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=🛡️ ESET`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=⚡ Speedtest`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🎥 奈飞节点`[]🐰 Disney节点`[]📹 油管节点`[]🧭 特殊节点
custom_proxy_group=⛏ Developer`select`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择`[]🔮 负载均衡`[]🇭🇰 香港策略`[]🇨🇳 台湾策略`[]🇯🇵 日本策略`[]🇰🇷 韩国策略`[]🇺🇲 美国策略`[]🇸🇬 狮城策略`[]DIRECT
custom_proxy_group=📹 油管节点`select`(Media|专线|港|Hong Kong|HK|台|Taiwan|TW|新加坡|Singapore|SG)
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media|专线|港|Hong Kong|HK|美|新加坡|Singapore|SG|台|Taiwan|TW|日|JP)
custom_proxy_group=🐰 Disney节点`select`(Media|专线|港|Hong Kong|HK|美|新加坡|Singapore|SG|台|Taiwan|TW|日|JP)
custom_proxy_group=🎬 Emby节点`select`(Media|专线|港|Hong Kong|HK|美|新加坡|Singapore|SG|台|Taiwan|TW|日|JP)
custom_proxy_group=🧭 特殊节点`select`(^(?!.*(港|台|日|韩|坡|美|HK|US|TW|JP|KR|KOR|SG|Hong Kong|Tai|Japan|Korea|Singapore|States|Expire|Traffic)).*)
custom_proxy_group=🇭🇰 香港策略`select`[]⏱ 香港延迟最低策略组`[]🚥 香港故障转移策略组`[]🎛 香港负载均衡策略组
custom_proxy_group=🇨🇳 台湾策略`select`[]⏱ 台湾延迟最低策略组`[]🚥 台湾故障转移策略组`[]🎛 台湾负载均衡策略组
custom_proxy_group=🇯🇵 日本策略`select`[]⏱ 日本迟最低策略组`[]🚥 日本故障转移策略组`[]🎛 日本负载均衡策略组
custom_proxy_group=🇰🇷 韩国策略`select`[]⏱ 韩国延迟最低策略组`[]🚥 韩国故障转移策略组`[]🎛 韩国负载均衡策略组
custom_proxy_group=🇺🇲 美国策略`select`[]⏱ 美国延迟最低策略组`[]🚥 美国故障转移策略组`[]🎛 美国负载均衡策略组
custom_proxy_group=🇸🇬 狮城策略`select`[]⏱ 狮城延迟最低策略组`[]🚥 狮城故障转移策略组`[]🎛 狮城负载均衡策略组
custom_proxy_group=⏱ 香港延迟最低策略组`url-test`(?=.*(港|HK|Hong Kong))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300,,10
custom_proxy_group=⏱ 台湾延迟最低策略组`url-test`(?=.*(台|新北|彰化|TW|Taiwan))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300,,10
custom_proxy_group=⏱ 日本迟最低策略组`url-test`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300,,10
custom_proxy_group=⏱ 韩国延迟最低策略组`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.apple.com/library/test/success.html`300,,10
custom_proxy_group=⏱ 美国延迟最低策略组`url-test`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300,,10
custom_proxy_group=⏱ 狮城延迟最低策略组`url-test`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300,,10
custom_proxy_group=🚥 香港故障转移策略组`fallback`(?=.*(港|HK|Hong Kong))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🚥 台湾故障转移策略组`fallback`(?=.*(台|新北|彰化|TW|Taiwan))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🚥 日本故障转移策略组`fallback`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🚥 韩国故障转移策略组`fallback`(KR|Korea|KOR|首尔|韩|韓)`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🚥 美国故障转移策略组`fallback`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🚥 狮城故障转移策略组`fallback`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🎛 香港负载均衡策略组`load-balance`(?=.*(港|HK|Hong Kong))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🎛 台湾负载均衡策略组`load-balance`(?=.*(台|新北|彰化|TW|Taiwan))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🎛 日本负载均衡策略组`load-balance`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🎛 韩国负载均衡策略组`load-balance`(KR|Korea|KOR|首尔|韩|韓)`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🎛 美国负载均衡策略组`load-balance`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300
custom_proxy_group=🎛 狮城负载均衡策略组`load-balance`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(标准)).)*$`http://www.apple.com/library/test/success.html`300

;设置分组标志位

; 在订阅时，通过指定 tag:xxx,URL (你的订阅链接) 将所有节点归属到名为xxx的分组。
; 分组设置完毕后，参考 rename=!!GROUP=xxx!!^@[你的前缀] 来为分组内节点添加前缀。
rename=!!GROUP=Kuromis!!^@[Kuromis]
rename=!!GROUP=FlowerCloud!!^@[FlowerCloud]
rename=!!GROUP=Amy!!^@[Amy]
rename=!!GROUP=Imm!!^@[Imm]

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/lonecale/Rules/main/Clash/Config/GeneralMihomoConfig.yml
;测速节点
;1. http://www.gstatic.com/generate_204
;2. http://cp.cloudflare.com/generate_204
;3. http://captive.apple.com/generate_204
;luck
